import assert from "node:assert/strict";
import { spawn, spawnSync } from "node:child_process";
import { once } from "node:events";
import { mkdtemp, mkdir, readFile, writeFile, rm, cp, readdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { createInterface } from "node:readline";
import { setTimeout as delay } from "node:timers/promises";
import { test } from "node:test";
import { pathToFileURL } from "node:url";

// This suite also runs in CI's no-submodule/no-node_modules delivery job.
test("process-local MCP reuse, Hook isolation, explicit writes and EOF cleanup", { timeout: 60000 }, async (t) => {
	const dir = await mkdtemp(join(tmpdir(), "codex-isolated-"));
	const root = join(dir, "project");
	const home = join(dir, "home");
	await mkdir(root); await mkdir(home);
	const cli = join(dir, "cli.mjs");
	await cp(resolve("dist/cli.js"), cli);
	const log = join(dir, "spawns");
	const config = join(home, "lsp-client.json");
	await writeFile(config, JSON.stringify({ trustedWorkspaces: [root], lsp: { fake: { command: [process.execPath, resolve("test/fixtures/fake-lsp.mjs")], extensions: [".fake"], env: { CODEX_LSP_TEST_LOG: log } } } }));
	await writeFile(join(root, "main.fake"), "broken\n");
	const env = { ...process.env, CODEX_HOME: home, CODEX_LSP_CACHE: join(dir, "cache"), LSP_TOOLS_MCP_USER_CONFIG: config };
	const children = [];
	t.after(async () => { for (const child of children) if (child.exitCode === null) child.kill(); await delay(200); await rm(dir, { recursive: true, force: true }); });
	const client = async () => {
		const child = spawn(process.execPath, [cli, "mcp"], {cwd: root, env, stdio: ["pipe", "pipe", "pipe"]});
		children.push(child);
		const exit = once(child, "exit");
		const responses = new Map();
		createInterface({input: child.stdout}).on("line", (line) => { const value = JSON.parse(line); responses.set(value.id, value); });
		let id = 0;
		const request = async (method, params) => {
			const key = ++id;
			child.stdin.write(`${JSON.stringify({jsonrpc: "2.0", id: key, method, params})}\n`);
			const deadline = performance.now() + 50000;
			while (performance.now() < deadline) {
				t.signal.throwIfAborted();
				if (responses.has(key)) return responses.get(key).result;
				assert.equal(child.exitCode, null, "MCP exited before responding");
				await delay(5, undefined, {signal: t.signal});
			}
			assert.fail(`MCP request timed out: ${method} ${params?.name ?? ""}`);
		};
		const init = await request("initialize", {});
		assert.equal(init.serverInfo.version, "0.4.0");
		return {request, async call(name, args = {}) { const result = await request("tools/call", {name, arguments: {workspace: root, session: "test", ...args}}); assert(!result.isError, JSON.stringify(result)); return result.content[0].text; }, async close() { child.stdin.end(); assert.deepEqual(await exit, [0, null]); }};
	};
	const hook = (event) => {
		const child = spawnSync(process.execPath, [cli, "hook"], { cwd: root, env, encoding: "utf8", timeout: 10000, input: JSON.stringify({ cwd: root, session_id: "test", turn_id: "t1", hook_event_name: event }) });
		assert.equal(child.status, 0, child.stderr);
		return child.stdout;
	};
	const first = await client();
	assert.equal(await readFile(log, "utf8").catch(() => ""), "", "initialize is lazy");
	assert.equal(hook("SessionStart"), "");
	await writeFile(join(root, "main.fake"), "broken again\n");
	assert.match(hook("PostToolUse"), /LSP not executed/);
	assert.equal(await readFile(log, "utf8").catch(() => ""), "", "Hook cannot launch LSP");
	assert.match(await first.call("check_diagnostics", {mode: "all"}), /pending/);
	assert.match(await first.call("lsp_diagnostics", {path: "main.fake"}), /fake\/E1/);
	assert.match(await first.call("lsp_diagnostics", {path: "main.fake"}), /fake\/E1/);
	assert.equal((await readFile(log, "utf8")).trim().split("\n").length, 1);
	const second = await client();
	assert.match(await second.call("check_diagnostics", {mode: "all"}), /pending/);
	await second.call("lsp_diagnostics", {path: "main.fake"});
	assert.equal((await readFile(log, "utf8")).trim().split("\n").length, 2);
	await second.close();
	assert.match(await first.call("lsp_format", {path: "main.fake"}), /Formatted/);
	assert.equal(await readFile(join(root, "main.fake"), "utf8"), "fixed! again\n");
	assert.match(await first.call("lsp_navigation", {path: "main.fake", operation: "rename", newName: "renamed"}), /Renamed/);
	assert.equal(await readFile(join(root, "main.fake"), "utf8"), "renamed again\n");
	const count = (await readFile(log, "utf8")).trim().split("\n").length;
	await first.call("lsp_diagnostics", {path: "main.fake", refresh: true});
	assert.equal((await readFile(log, "utf8")).trim().split("\n").length, count + 1);
	await Promise.all(Array.from({length: 201}, (_,i) => writeFile(join(root, `page-${i}.fake`), "x")));
	const page = await first.call("lsp_diagnostics", {path: "."});
	assert.match(page, /^partial;/);
	assert.match(page, /next start=200/);
	const revision = /revision=([a-f0-9]+)/.exec(page)[1];
	assert.match(await first.call("lsp_diagnostics", {path: ".", start: 200, revision}), /revision=/);
	await first.close();
	for (const pid of (await readFile(log, "utf8")).trim().split("\n").map(Number)) assert.throws(() => process.kill(pid, 0));
});

test("MCP cancellation, partial writes, schema errors and recovery through the delivered bundle", {timeout: 30000}, async (t) => {
	const dir = await mkdtemp(join(tmpdir(), "codex-cancel-e2e-"));
	const root = join(dir, "project"); await mkdir(root);
	const cli = join(dir, "cli.mjs"); await cp(resolve("dist/cli.js"), cli);
	const log = join(dir, "spawns");
	const config = join(dir, "user.json");
	const configure = (mode) => writeFile(config, JSON.stringify({trustedWorkspaces: [root], lsp: {fake: {command: [process.execPath, resolve("test/fixtures/fake-lsp.mjs")], extensions: [".fake"], env: {CODEX_LSP_TEST_LOG: log, CODEX_LSP_TEST_MODE: mode}}}}));
	await configure("slow");
	await writeFile(join(root, "a.fake"), "broken\n");
	await writeFile(join(root, "b.fake"), "broken\n");
	const preload = join(dir, "delay-write.mjs");
	await writeFile(preload, 'import fs from "node:fs/promises";import {syncBuiltinESMExports} from "node:module";const original=fs.writeFile;fs.writeFile=async (...args)=>{await original(...args);if(String(args[0]).endsWith("a.fake")) await new Promise(r=>setTimeout(r,400));};syncBuiltinESMExports();');
	const child = spawn(process.execPath, ["--import", pathToFileURL(preload).href, cli, "mcp"], {cwd: root, env: {...process.env, LSP_TOOLS_MCP_USER_CONFIG: config, CODEX_LSP_CACHE: join(dir, "cache")}, stdio: ["pipe", "pipe", "pipe"]});
	const exited = once(child, "exit");
	t.after(async () => {if(child.exitCode === null) {child.kill(); await exited;} await rm(dir, {recursive: true, force: true});});
	const results = new Map();
	let stderr = ""; child.stderr.setEncoding("utf8").on("data", chunk => {stderr += chunk;});
	createInterface({input: child.stdout}).on("line", (line) => {const value = JSON.parse(line); results.set(value.id, value.result);});
	const until = async (condition) => {for(let i=0;i<2000;i++){if(await condition())return;await delay(5);}assert.fail(`Timed out; exit=${child.exitCode}; responses=${JSON.stringify([...results])}; stderr=${stderr}`);};
	let sequence = 0;
	const send = (method, params, id) => child.stdin.write(`${JSON.stringify({jsonrpc:"2.0", ...(id === undefined ? {} : {id}), method, params})}\n`);
	const begin = (name, args) => {const id=++sequence;send("tools/call", {name,arguments:{workspace:root,session:"s",...args}},id);return id;};
	const result = async (id) => {await until(()=>results.has(id));return results.get(id);};
	const cancel = (id) => send("notifications/cancelled", {requestId:id});
	const pids = async () => (await readFile(log,"utf8").catch(()=>"")).trim().split("\n").filter(Boolean).map(Number);
	const alive = (pid) => {try{process.kill(pid,0);return true;}catch{return false;}};
	for (const args of [{mode:"all",refresh:true},{mode:"status",refresh:false},{mode:"full",refresh:"yes"}]) {
		assert.equal((await result(begin("check_diagnostics", args))).isError,true);
	}
	const first = begin("lsp_diagnostics", {path:"a.fake"});
	await until(async ()=>(await pids()).length===1);
	const queued = begin("lsp_diagnostics", {path:"b.fake"});
	cancel(queued);
	assert.match((await result(queued)).content[0].text,/cancelled|aborted/i);
	assert(alive((await pids())[0]),"queued cancellation cannot kill the active LSP");
	cancel(first);
	assert.equal((await result(first)).isError,true);
	await until(async ()=>(await pids()).every(pid=>!alive(pid)));
	assert.equal((await pids()).length,1,"cancelled queued request never starts a client");

	await configure("slow-second");
	const formatting=begin("lsp_format",{paths:["a.fake","b.fake"]});
	await until(async ()=>(await readFile(join(root,"a.fake"),"utf8")).startsWith("fixed!"));
	cancel(formatting);
	const partial=await result(formatting);
	assert.equal(partial.isError,true);
	assert.match(partial.content[0].text,/Formatted: a.fake/);
	assert.equal(await readFile(join(root,"b.fake"),"utf8"),"broken\n");

	await writeFile(join(root,"a.fake"),"broken\n");
	await configure("two-files");
	const rename=begin("lsp_navigation",{path:"a.fake",operation:"rename",newName:"renamed"});
	await until(async ()=>(await readFile(join(root,"a.fake"),"utf8")).startsWith("renamed"));
	cancel(rename);
	const partialRename=await result(rename);
	assert.equal(partialRename.isError,true);
	assert.match(partialRename.content[0].text,/modified paths: a.fake/);
	assert.equal(await readFile(join(root,"b.fake"),"utf8"),"broken\n");

	await configure("");
	const checked=await result(begin("lsp_diagnostics",{path:"b.fake",refresh:true}));
	assert(!checked.isError,JSON.stringify(checked));
	assert.match(checked.content[0].text,/fake\/E1/);
	child.stdin.end();
	assert.deepEqual(await exited,[0,null]);
	assert((await pids()).every(pid=>!alive(pid)),"EOF cleans every analysis process");
});

test("short Hook budget, pending recovery, Stop deduplication and concurrent metadata", {timeout: 30000}, async (t) => {
	const dir=await mkdtemp(join(tmpdir(),"codex-hook-e2e-"));
	t.after(()=>rm(dir,{recursive:true,force:true}));
	const root=join(dir,"project");await mkdir(root);
	const cli=join(dir,"cli.mjs");await cp(resolve("dist/cli.js"),cli);
	const config=join(dir,"user.json");
	await writeFile(config,JSON.stringify({trustedWorkspaces:[root],lint:{javascript:"biome"}}));
	await writeFile(join(root,"biome.json"),"{}");
	const bin=join(root,"node_modules/@biomejs/biome/bin");await mkdir(bin,{recursive:true});
	const log=join(dir,"runners");
	await writeFile(join(bin,"biome"),`const fs=require("node:fs");fs.appendFileSync(${JSON.stringify(log)},process.pid+"\\n");const content=fs.readFileSync(process.argv.at(-1),"utf8");if(content==="slow")setInterval(()=>{},1000);else console.log(JSON.stringify({diagnostics:[{severity:content==="error"?"error":"warning",description:"fixture finding",category:"fixture"}]}));`);
	await writeFile(join(root,"main.js"),"baseline");
	const cache=join(dir,"cache");
	const env={...process.env,LSP_TOOLS_MCP_USER_CONFIG:config,CODEX_LSP_CACHE:cache,CODEX_LSP_TRUST_PROJECT:"0"};
	const hook=(event,extra={},imports=[])=>new Promise((resolve,reject)=>{
		const child=spawn(process.execPath,[...imports,cli,"hook"],{cwd:root,env,stdio:["pipe","pipe","pipe"]});
		let output="";let error="";
		child.stdout.setEncoding("utf8").on("data",chunk=>{output+=chunk;});
		child.stderr.setEncoding("utf8").on("data",chunk=>{error+=chunk;});
		child.once("error",reject);
		child.once("exit",code=>{if(code!==0)reject(new Error(error));else resolve(output);});
		child.stdin.end(JSON.stringify({cwd:root,session_id:"s",hook_event_name:event,...extra}));
	});
	const metadata=async()=>{
		const files=(await readdir(cache,{recursive:true})).filter(file=>file.endsWith(".json"));
		assert.equal(files.length,1);
		const raw=await readFile(join(cache,files[0]),"utf8");
		assert(!raw.includes("fixture finding"),"findings cannot be persisted");
		return JSON.parse(raw);
	};
	assert.equal(await hook("SessionStart"),"");
	await writeFile(join(root,"main.js"),"slow");
	const started=performance.now();
	assert.match(await hook("PostToolUse"),/budget|pending/i);
	assert(performance.now()-started<8000,"Hook total execution stays below host timeout");
	assert((await metadata()).pending.includes("main.js"));
	for(const pid of (await readFile(log,"utf8")).trim().split("\n").map(Number))assert.throws(()=>process.kill(pid,0));
	await writeFile(join(root,"main.js"),"warning");
	assert.match(await hook("PostToolUse"),/LSP not executed/);
	assert.deepEqual((await metadata()).pending,[]);
	assert.equal(await hook("Stop"),"","warning never blocks");
	await writeFile(join(root,"main.js"),"error");
	assert.equal(JSON.parse(await hook("Stop")).decision,"block");
	assert.equal(await hook("Stop"),"","fresh error blocks only once");
	await writeFile(join(root,"a.js"),"warning");await writeFile(join(root,"b.js"),"warning");
	await Promise.all([hook("PostToolUse"),hook("PostToolUse"),hook("PostToolUse")]);
	const state=await metadata();
	assert(state.touched.includes("a.js")&&state.touched.includes("b.js"));
	assert.match(await hook("PostToolUse",{session_id:undefined}),/session_id/);
	const crash=join(dir,"crash-update.mjs");
	await writeFile(crash, 'import fs from "node:fs/promises";import {syncBuiltinESMExports} from "node:module";const original=fs.rename;fs.rename=async(from,to)=>{if(String(to).endsWith(".json")){process.kill(process.pid,"SIGKILL");await new Promise(()=>{});}return original(from,to);};syncBuiltinESMExports();');
	await writeFile(join(root,"main.js"),"warning");
	await assert.rejects(hook("PostToolUse",{},["--import",pathToFileURL(crash).href]));
	await Promise.all([hook("PostToolUse"),hook("PostToolUse")]);
	assert.deepEqual((await metadata()).pending,[],"dead writer locks recover without losing state");
	await hook("SessionEnd");assert.deepEqual((await metadata()).touched,[]);
	await hook("SessionStart");assert.notEqual((await metadata()).turn,"__ended__");
});
